### ISSUE TITLE
7.11 crashes when swiping to the sidebar

### ISSUE THREAD

**Issue by royerlraph79** [JMccormick264/TwitterPP#2]
When I try to show the sidebar on the left or when I press on my profile icon, the app crashes. Doesn’t do that on 7.10.

**Comment by JMccormick264** [comment]
Thank you. I made an issue report along with the crash log [here](https://github.com/eni9889/TW-PP-Issues/issues/26)

**Comment by JMccormick264** [comment]
@royerlraph79 Update to the latest [here](https://github.com/JMccormick264/TwitterPP/releases/tag/7.11.1_v1.2r-70) Issue has been fixed with the latest tweak update
